export const data = [
  {
    id: 'RT3080',
    invoiceDate: '2021-08-18:01:00.000Z',
    description: 'Re-branding',
    paymentTerms: 1,
    clientName: 'Jensen Huang',
    clientEmail: 'jensenh@mail.com',
    status: 'paid',
    senderStreet: '19 Union Terrace',
    senderCity: 'London',
    senderPostCode: 'E1 3EZ',
    senderCountry: 'United Kingdom',
    clientStreet: '106 Kendell Street',
    clientCity: 'Sharrington',
    clientPostCode: 'NR24 5WQ',
    clientCountry: 'United Kingdom',
  },
  {
    id: 'XM9141',
    invoiceDate: '2021-08-18:01:00.000Z',
    description: 'Graphic Design',
    paymentTerms: 30,
    clientName: 'Alex Grim',
    clientEmail: 'alexgrim@mail.com',
    status: 'pending',
    senderStreet: '19 Union Terrace',
    senderCity: 'London',
    senderPostCode: 'E1 3EZ',
    senderCountry: 'United Kingdom',
    clientStreet: '84 Church Way',
    clientCity: 'Bradford',
    clientPostCode: 'BD1 9PB',
    clientCountry: 'United Kingdom',
  },
  {
    id: 'RG0314',
    invoiceDate: '2021-08-18:01:00.000Z',
    description: 'Website Redesign',
    paymentTerms: 7,
    clientName: 'John Morrison',
    clientEmail: 'jm@myco.com',
    status: 'paid',
    senderStreet: '19 Union Terrace',
    senderCity: 'London',
    senderPostCode: 'E1 3EZ',
    senderCountry: 'United Kingdom',
    clientStreet: '84 Church Way',
    clientCity: 'Bradford',
    clientPostCode: 'BD1 9PB',
    clientCountry: 'United Kingdom',
  },
  {
    id: 'RT2080',
    invoiceDate: '2021-08-18:01:00.000Z',
    description: 'Logo Concept',
    paymentTerms: 1,
    clientName: 'Alysa Werner',
    clientEmail: 'alysa@email.co.uk',
    status: 'pending',
    senderStreet: '19 Union Terrace',
    senderCity: 'London',
    senderPostCode: 'E1 3EZ',
    senderCountry: 'United Kingdom',
    clientStreet: '84 Church Way',
    clientCity: 'Bradford',
    clientPostCode: 'BD1 9PB',
    clientCountry: 'United Kingdom',
  },
  {
    id: 'AA1449',
    invoiceDate: '2021-08-18:01:00.000Z',
    description: 'Re-branding',
    paymentTerms: 7,
    clientName: 'Mellisa Clarke',
    clientEmail: 'mellisa.clarke@example.com',
    status: 'pending',
    senderStreet: '19 Union Terrace',
    senderCity: 'London',
    senderPostCode: 'E1 3EZ',
    senderCountry: 'United Kingdom',
    clientStreet: '84 Church Way',
    clientCity: 'Bradford',
    clientPostCode: 'BD1 9PB',
    clientCountry: 'United Kingdom',
  },
  {
    id: 'TY9141',
    invoiceDate: '2021-08-18:01:00.000Z',
    description: 'Landing Page Design',
    paymentTerms: 30,
    clientName: 'Thomas Wayne',
    clientEmail: 'thomas@dc.com',
    status: 'pending',
    senderStreet: '19 Union Terrace',
    senderCity: 'London',
    senderPostCode: 'E1 3EZ',
    senderCountry: 'United Kingdom',
    clientStreet: '84 Church Way',
    clientCity: 'Bradford',
    clientPostCode: 'BD1 9PB',
    clientCountry: 'United Kingdom',
  },
  {
    id: 'FV2353',
    invoiceDate: '2021-08-18:01:00.000Z',
    description: 'Logo Re-design',
    paymentTerms: 7,
    clientName: 'Anita Wainwright',
    clientEmail: '',
    status: 'draft',
    senderStreet: '19 Union Terrace',
    senderCity: 'London',
    senderPostCode: 'E1 3EZ',
    senderCountry: 'United Kingdom',
    clientStreet: '84 Church Way',
    clientCity: 'Bradford',
    clientPostCode: 'BD1 9PB',
    clientCountry: 'United Kingdom',
  },
];
